before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: SSxJcJkFSrlHGrz7O6P4ZUdWDYNZQJ3vL+Ui9s8SKT8huL7SgTQT4SK/BMa5IFl+84X2oi3GOIUXBYPBMYoIFK7dYz66UQpyBXuJt54JoR9Ll+Wr7eHfCKJfStgEaZTBBsS4maFM8E3YM7Atj0etKfWw9Dzgzr5q2LTQTNgplgXDxGDLRWb6nEx9OidSZtEX6pOx+CpL9sBLOSSvXc6UfMZLz7DjFOPwfmGrxA0QmrgndwRTL720Xxy+R1TnvKqwErHorzxg0svPx/NIVHJ0Ap3HjPWShHLxvWNiP853Qg/wxMIDSau3bR4ALJ0+NjSTl1Zlhtg6HJkHl0l4raw0Hv8oVeX7Mu03/E2CH6AK80SWkc+yUX++Hd6mJxiM2SWAcDMXOIfVWnOXBrMNUMS5UcajmBfQRhote6RpzyJou6iIZEf1zTs/NJEZ7gKOhbNpY5MqabJpI1Rw84HYAr2VlChL/2VcrpnyFISu8MFXfV+nc2fyPARoPGoYqhNlhay7b9UPCsrGEnsFZZXorxVzrq3sPQ/jv83+XDD+1Py1Xp8+nevg5pjN7N4GoLACvVKg6U+eT1Ij960N95UQecjVkQgKfXhbYf9GsJLUNETIPbF5g79hSKiDdHxJ07gbDpubTjKK/KejMlv0pL6g0uzoe0XfDnUCFTeZvN+EhxYlszs= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
